### ISSUE TITLE
ci: GitHub Action Workflows to manage code

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/wrappid-app#10]
## Description
We will create GitHub Action Workflows workflows to do the followings:
- [x] Linting check on pull request
- [x] Check successfully created build
- [x] Test (Functionality missing as of now.)
- [x] Deploy (when merge into main from dev)

**Comment by anantakumarghosh** [comment]
Currently stage wrappid-app deploy is manual

**Comment by techoneel** [comment]
As discussed with @anantakumarghosh closing this issue as all tasks is completed.
