### ISSUE TITLE
docs: Need ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by PritamBag** [wrappid/wrappid-app#124]
**Is your feature request related to a problem? Please describe.**
ISSUE_TEMPLATE is missing in this repository

**Describe the solution you'd like**
There is a need for an ISSUE_TEMPLATE, so adding such a template helps the user or contributor when they are raising an issue

**Describe alternatives you've considered**
Adding an ISSUE_TEMPLATE is the best solution for this, So adding an ISSUE_TEMPLATE is needed

**Comment by PritamBag** [comment]
@anantakumarghosh please make sure the development branch is merged with main so that people can get the benefit of the pull request.

**Comment by anantakumarghosh** [comment]
> @anantakumarghosh please make sure the development branch is merged with main so that people can get the benefit of the pull request.

development branch is already merged with main.
