### ISSUE TITLE
bug: the body and the navbar are overlapping

### ISSUE THREAD

**Issue by arkaprota** [wrappid/wrappid-app#129]
**Describe**

the body and the header are overlapping for that reason the upper part of the body is not visible and the body is coming under the navbar section
![Screenshot 2024-07-15 163651](https://github.com/user-attachments/assets/e4973dae-3463-4bee-8719-9731712f39e1)

**Comment by techoneel** [comment]
This is a temporary fixed and we need create a separate issue for WrappidAppLayout restructuring.

Closing this issue since the problem with this layout has been fixed.
