### ISSUE TITLE
documentation: Removed mui components.

### ISSUE THREAD

**Issue by irkfaisal** [wrappid/wrappid-app#13]
## Is your feature request related to a problem? Please describe.
There are mui components imports in files like CoreButton.docs.js, CoreAvatar.docs.js, CoreSwitch.docs.js and CoreRating.docs.js.

## Describe the solution you'd like
Removed mui imports from the file.

**Comment by irkfaisal** [comment]
this issue is related to issue  #https://github.com/wrappid/guide-module/issues/13 mistakenly created in wrappid-app.

**Comment by samhere17** [comment]
@irkfaisal in such scenarios, if you mistakenly create issue in some other repo, you may transfer it to the actual repo.


<img width="193" alt="image" src="https://github.com/wrappid/wrappid-app/assets/3071968/79eb7de4-c916-46e0-9d38-17d0d7b0174b">
