### ISSUE TITLE
bug: the nav bar is with the body section

### ISSUE THREAD

**Issue by arkaprota** [wrappid/wrappid-app#130]
**Describe**

the body section is coming under the navbar instead it is overlapping for which we are not able the see the full content
![Screenshot 2024-07-15 163651](https://github.com/user-attachments/assets/1d086773-04aa-4c04-89dc-c9e885b2f8c8)

**Comment by techoneel** [comment]
This issue is repetitive https://github.com/wrappid/wrappid-app/issues/129.
