### ISSUE TITLE
bug: StaticWebPage is not rendering in mobile

### ISSUE THREAD

**Issue by Edithmark42** [wrappid/wrappid-app#15]
**Description:**
The StaticWebPage having CoreStack which is not yet fixxed in native-mobile.

**Solution:**
1. The CoreStack needs to be fixed in native-mobile
2. The CoreStack needs to be changed to CoreBox until it's fixed.

**Comment by techoneel** [comment]
This issue is dependent on https://github.com/wrappid/wrappid-app/issues/17

**Comment by Edithmark42** [comment]
Kindly check this issue and take any necessary steps to resolve it. @irkfaisal

**Comment by techoneel** [comment]
closing this issue since the branch is merged, will re-open if required
