### ISSUE TITLE
feature: add version in static wrappid-app

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/wrappid-app#17]
I cannot understand which current version i am testing @wrappid/devops-team

_Originally posted by @Animesh1432 in https://github.com/wrappid/guide-module/issues/6#issuecomment-1880858480_
            
## Description
In Static wrappid app, there is no option to see app version.

**Comment by Edithmark42** [comment]
@irkfaisal as you are working on the versioning, I am assigning you to this issue. If you need any help, kindly contact me.

**Comment by techoneel** [comment]
The above issue mentioned in https://github.com/wrappid/wrappid-app/issues/32 and it's resolved so I'm closing this issue as of now.
