### ISSUE TITLE
feature: Add button/ link to access guide/styles and guide/components.

### ISSUE THREAD

**Issue by Edithmark42** [wrappid/wrappid-app#21]
Problem 
- There are no navigation button or link in the homepage of wrappid-app for opening styles and components pages. _Originally posted by @Animesh1432 in https://github.com/wrappid/guide-module/issues/6#issuecomment-1880506858_

Solution
- Adding Buttons for the navigation purpose.

**Comment by Animesh1432** [comment]
pass

**Comment by techoneel** [comment]
this issue is closed as of now
