### ISSUE TITLE
feature: wrappid-app template versioning

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/wrappid-app#23]
## Description
Currently there is no template versioning, so there is no way to know which template version user's wrappid-app is using. 

## Proposed solution
Add templateVersion key in package.json

## Update 6 Feb 2024
Use wrTemplateVersion key in package.json

## Update 14 March 2024
Use wrTemplateVersion key in wrappid.meta.json

**Comment by techoneel** [comment]
@anantakumarghosh is still working on this as of now

**Comment by anantakumarghosh** [comment]
Closing as done.
