### ISSUE TITLE
enhancement: create a page that will show the versions.

### ISSUE THREAD

**Issue by irkfaisal** [wrappid/wrappid-app#32]
Create a page that will show us all the versions of current application and wrappid packages versions with all the basic details.

The page should contain all the details of current application with application name, version, author name, homepage URL , repository link and description in a separate  section section.
Then we will have the two section one for wrappid  packages and another for non wrappid packages. This will be an accordion and all the details inside the  wrappid  packages and non wrappid packages should also grouped by accordions.
The details inside the grouped accordion should be below points.
1.  version
2. name
3. author
4. dependencies
5. dev-dependencies
6. package homepage URL
7. repository URL
8. bug report URL
9. development versions

**Comment by irkfaisal** [comment]
page created according to the description. May open again if required for further enhancement.

**Comment by Edithmark42** [comment]
## project title and details are undefined in the about page.
![image](https://github.com/wrappid/wrappid-app/assets/58048663/2e36cd53-172b-49b0-aced-a7f35dcb5d1b)

**Comment by Edithmark42** [comment]
Help resources: 
https://stackoverflow.com/questions/45978230/get-version-number-from-package-json-in-react-redux-create-react-app

**Comment by irkfaisal** [comment]
creating a new design according to the ref: https://docs.google.com/presentation/d/1WylglV48o6Z50O7EwcPutOnA_ePZpFj5hgM6Kz3U1m8/edit#slide=id.g1f19dbf7b29_0_0
with mobile first approach.

**Comment by techoneel** [comment]
@samhere17 update the issue description what needs to be done
