### ISSUE TITLE
bug: remove 'usingSmallUtilityStyles' in wrappid-app

### ISSUE THREAD

**Issue by irkfaisal** [wrappid/wrappid-app#43]
### Description
remove 'usingSmallUtilityStyles' from
-src
  -styles
  -DefaultAppStyles.js
  -LargeAppStyles.js
  -LargeAppStyles.js
  -LargeAppStyles.js
  -XLargeAppStyles.js
  -XXLargeAppStyles.js

**Comment by techoneel** [comment]
closing this issue since the changes are done
