### ISSUE TITLE
enchancement: Add Application Registry

### ISSUE THREAD

**Issue by anantakumarghosh** [wrappid/wrappid-app#5]
## Description
In App.js, import Application Registry and add in core app

**Comment by techoneel** [comment]
this issues got resolved and tested [cfa36fdb51b8273c6283ffbea32b32fdbab2345c](https://github.com/wrappid/core/commit/cfa36fdb51b8273c6283ffbea32b32fdbab2345c) and https://github.com/wrappid/wrappid-app/commit/ad3526c23e536a38b8f7ada3e12046f93fafa1cb
