### ISSUE TITLE
bug: boilerplate page ui

### ISSUE THREAD

**Issue by Animesh1432** [wrappid/wrappid-app#68]
Title - Check [Wrappid Demo](https://demo.wrappid.dev/) page
Module: @techoneel please write the module name
Feature: Boilerplate Page

Issues -

- [ ] #113

![image](https://github.com/wrappid/wrappid-app/assets/105671990/d55f3dfa-1a61-4c88-8627-a28c18a9e882)

- [x] 2. Incomplete Divider 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/6107cc79-dc11-42e6-946e-5502749a53f3)
- [x] 3. Full stop missing
![image](https://github.com/wrappid/wrappid-app/assets/105671990/4b5cc652-d999-4a7e-9a0a-6fe2d8fb6f73)
- [ ] 4. Spacing between logo and description is not same like other gaps
![image](https://github.com/wrappid/wrappid-app/assets/105671990/28c0a6e1-9df5-4631-be49-0f847fa28ca4)
- [ ] 5. why there is no space between the tagline and version ?? looks not good
![image](https://github.com/wrappid/wrappid-app/assets/105671990/9d9cda4a-608b-4ab7-b9e9-84a0ac1929eb)
- [ ] 6. Different Font
![image](https://github.com/wrappid/wrappid-app/assets/105671990/c7cf379e-f958-4468-a44d-590d1c06bb79)
- [ ] 7. Font size should not be same of page heading and sub headings
![image](https://github.com/wrappid/wrappid-app/assets/105671990/9b44f4f7-2669-459b-8762-09ca2088243d)
![image](https://github.com/wrappid/wrappid-app/assets/105671990/dfac30c5-ba9b-4364-a806-f7d16d9f5296)
- [ ] 8. Too much padding
![image](https://github.com/wrappid/wrappid-app/assets/105671990/c3cb228a-a5db-4c89-94a1-f57d42d66c03)
- [ ] 9. Font color: why the font colors of these words are different ?? they are not linked with anything. 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/9239aefa-f095-4ec6-81a8-46292c6227a7)
- [ ] 10. button: A button should navigate a new page from starting but the "How to customize" button shows the new page but not from starting. it shows new page as respect of the button position in the wrappid boilerplate page.
- [ ] 11. different button size 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/899a1286-d44d-4df1-b032-bf3e662b0e80)
![image](https://github.com/wrappid/wrappid-app/assets/105671990/debb6875-94b8-4f0b-8370-4b2e29fd18c6)
- [ ] 12. too much space 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/c8555813-6bc3-4cad-ac1d-2699effbfd98)
- [ ] 13. why there is 4 type of font size ??
![image](https://github.com/wrappid/wrappid-app/assets/105671990/ff0889af-aac2-4e38-aae6-ce0653b9008c)
- [ ] 14. Extra divider 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/73ef9fec-d291-412f-9e59-091f70161f9f)
- [ ] 15. different color 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/015bcf02-97e5-47cc-867b-ff414bf230ba)
- [ ] 16. after clicking theme button this shows
![image](https://github.com/wrappid/wrappid-app/assets/105671990/968d18ec-5e3d-4844-94d2-9eb02b088171)
- [ ] 17. User cannot understand theme as a button
- [x] 18. 2 different wrappid theme 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/a234b9c1-3420-4db3-8b18-285b437980ec)
![image](https://github.com/wrappid/wrappid-app/assets/105671990/47b81ea3-86fb-4d7f-95cd-8ee48bbfddc9)
- [x] 19. 2 different theme 1
![image](https://github.com/wrappid/wrappid-app/assets/105671990/f3d68ecc-651f-4a7d-ac31-4cfd58b34514)
![image](https://github.com/wrappid/wrappid-app/assets/105671990/aaac77db-258c-4f73-8217-83e50489db1c)
- [ ] 20. Demo shoukld be in upper case 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/177bf9ab-8c82-46ee-b3b6-88f42ec3c91f)
- [ ] 21. theme 1 gapping issue
![image](https://github.com/wrappid/wrappid-app/assets/105671990/1a33c2d5-382f-44cd-a10b-44b0c7c28888)

|  Key  |  Value  |
| ---- | ---- |
| Fronend URL | https://demo.wrappid.dev/ |
| Fronend Version | 0.0.45-dev.2 |
| Backend URL |  |
| Backend Version |  |

System :

|  Key  |  Value  |
| ---- | ---- |
| OS | Windows 10 |
| Browser | Google Chrome |
| Version | 121.0.6167.162 |

**Comment by Animesh1432** [comment]
Issues -
1. Need spacing between header and wrappid logo 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/d55f3dfa-1a61-4c88-8627-a28c18a9e882)
2. Incomplete Divider 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/6107cc79-dc11-42e6-946e-5502749a53f3)
3. Full stop missing
![image](https://github.com/wrappid/wrappid-app/assets/105671990/4b5cc652-d999-4a7e-9a0a-6fe2d8fb6f73)
4. Spacing between logo and description is not same like other gaps
![image](https://github.com/wrappid/wrappid-app/assets/105671990/28c0a6e1-9df5-4631-be49-0f847fa28ca4)
5. why there is no space between the tagline and version ?? looks not good
![image](https://github.com/wrappid/wrappid-app/assets/105671990/9d9cda4a-608b-4ab7-b9e9-84a0ac1929eb)
6. Different Font
![image](https://github.com/wrappid/wrappid-app/assets/105671990/c7cf379e-f958-4468-a44d-590d1c06bb79)
7. Font size should not be same of page heading and sub headings
![image](https://github.com/wrappid/wrappid-app/assets/105671990/9b44f4f7-2669-459b-8762-09ca2088243d)
![image](https://github.com/wrappid/wrappid-app/assets/105671990/dfac30c5-ba9b-4364-a806-f7d16d9f5296)
8. Too much padding
![image](https://github.com/wrappid/wrappid-app/assets/105671990/c3cb228a-a5db-4c89-94a1-f57d42d66c03)
9. Font color: why the font colors of these words are different ?? they are not linked with anything. 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/9239aefa-f095-4ec6-81a8-46292c6227a7)
10. button: A button should navigate a new page from starting but the "How to customize" button shows the new page but not from starting. it shows new page as respect of the button position in the wrappid boilerplate page.
11. different button size 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/899a1286-d44d-4df1-b032-bf3e662b0e80)
![image](https://github.com/wrappid/wrappid-app/assets/105671990/debb6875-94b8-4f0b-8370-4b2e29fd18c6)
12. too much space 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/c8555813-6bc3-4cad-ac1d-2699effbfd98)
13. why there is 4 type of font size ??
![image](https://github.com/wrappid/wrappid-app/assets/105671990/ff0889af-aac2-4e38-aae6-ce0653b9008c)
14. Extra divider 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/73ef9fec-d291-412f-9e59-091f70161f9f)
15. different color 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/015bcf02-97e5-47cc-867b-ff414bf230ba)
16. after clicking theme button this shows
![image](https://github.com/wrappid/wrappid-app/assets/105671990/968d18ec-5e3d-4844-94d2-9eb02b088171)
17. User cannot understand theme as a button
18. 2 different wrappid theme 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/a234b9c1-3420-4db3-8b18-285b437980ec)
![image](https://github.com/wrappid/wrappid-app/assets/105671990/47b81ea3-86fb-4d7f-95cd-8ee48bbfddc9)
19. 2 different theme 1
![image](https://github.com/wrappid/wrappid-app/assets/105671990/f3d68ecc-651f-4a7d-ac31-4cfd58b34514)
![image](https://github.com/wrappid/wrappid-app/assets/105671990/aaac77db-258c-4f73-8217-83e50489db1c)
20. Demo shoukld be in upper case 
![image](https://github.com/wrappid/wrappid-app/assets/105671990/177bf9ab-8c82-46ee-b3b6-88f42ec3c91f)



|  Key  |  Value  |
| ---- | ---- |
| Fronend URL | https://demo.wrappid.dev/ |
| Fronend Version | 0.0.45-dev.2 |
| Backend URL |  |
| Backend Version |  |

System :

|  Key  |  Value  |
| ---- | ---- |
| OS | Windows 10 |
| Browser | Google Chrome |
| Version | 121.0.6167.162 |

**Comment by santapan345** [comment]
Can I work on this issue?

**Comment by techoneel** [comment]
@Animesh1432 please update the issue description.

@Edithmark42 please share the present status of the issue.

@santapan345 thanks for showing interest.
After they update the current status you can work on the issue.

**Comment by Edithmark42** [comment]
- [ ] marked issues are already resolved.
- [ ] marked issues need to be resolved.

**Comment by Edithmark42** [comment]
@santapan345 
> Can I work on this issue?

@Animesh1432 updated the issue description and @Edithmark42 updated the current status of the issue. You can work on any unresolved issues.

Please feel free to comment for any question and concerns.

**Comment by Edithmark42** [comment]
> Can I work on this issue?

@santapan345 the issue description was updated. You may work on the remaining issues.
