### ISSUE TITLE
enhancement: route, theme and layout related changes

### ISSUE THREAD

**Issue by techoneel** [wrappid/wrappid-app#75]
- [x] Cleanup of unwanted files
  - [x] theme.conf.json
  - [x] cgpt.mui-theme.conf.json
- [x] Added below keys to config
  - [x] defaultRoute
  - [x] defaultAuthenticatedRoute
  - [x] defaultLayout
  - [x] defaultAuthenticatedLayout

**Comment by irkfaisal** [comment]
closing this issue (code has been merged)
